title: ORANGE UFO
description: 个人独立博客
author: 橙色飞碟
github: https://github.com/OrangeUFO
me: http://www.orangeufo.com
about: 一个非职业量化交易员，使用Python语言，主要分享一些策略以及学习笔记。
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-envelope
      link: "mailto:chenhuijie23@qq.com"
    - icon: fa-envira
      link: "http://xueqiu.com/orangeufo"
    - icon: fa-weibo
      link: "http://weibo.com/chenhuijie23"
    - icon: fa-angellist
      link: "http://www.douban.com/people/OrangeUFO/"
    - icon: fa-github
      link: "https://github.com/orangeufo"

urls:
    - text: 关于
      url: /about/
    - text: 我的项目
      url: /projects/
    - text: 订阅我的小站
      url: /feed.xml

url: "http://www.orangeufo.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
