title: ORANGE UFO
description: 我的个人网站
author: 橙色飞碟
github: https://github.com/OrangeUFO
about: 人是生而自由的，但却无往而不在枷锁之中
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-music
      link: "http://music.163.com/#/user/home?id=405440407"
    - icon: fa-weibo
      link: "http://weibo.com/5305382808/profile?topnav=1&wvr=6&is_all=1"
    - icon: fa-renren
      link: "http://www.douban.com/people/OrangeUFO/"
    - icon: fa-stack-exchange
      link: "http://www.douban.com/people/OrangeUFO/"
    - icon: fa-github
      link: "https://github.com/orangeufo"

share:
  twitter_username: 
  fb_appid: 

urls:
    - text: 关于我
      url: /about/
    - text: 我的项目
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "http://www.orangeufo.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
