title: ORANGE UFO
description: 我的个人网站
author: 橙色飞碟
github: https://github.com/OrangeUFO
douban: http://www.douban.com/people/OrangeUFO/
about: 人是生而自由的，但却无往而不在枷锁之中
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-envelope
      link: "mailto:chenhuijie23@qq.com"
    - icon: fa-weibo
      link: "http://www.douban.com/people/OrangeUFO/"
    - icon: fa-camera
      link: "http://www.douban.com/people/OrangeUFO/photos"

urls:
    - text: 关于我
      url: /about/
    - text: 我的项目
      url: /projects/
    - text: RSS订阅
      url: /feed.xml

url: "http://www.orangeufo.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
