title: ORANGE UFO
description: 我的个人网站
author: 橙色飞碟
github: https://github.com/OrangeUFO
douban: http://www.orangeufo.com
about: 欢迎来到我的个人网站~
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-envelope
      link: "mailto:chenhuijie23@qq.com"
    - icon: fa-envira
      link: "http://www.jianshu.com/users/091d9edf6147/timeline"
    - icon: fa-weibo
      link: "http://weibo.com/chenhuijie23"
    - icon: fa-angellist
      link: "http://www.douban.com/people/OrangeUFO/"
    - icon: fa-github
      link: "https://github.com/orangeufo"

urls:
    - text: 关于我
      url: /about/
    - text: 我的项目
      url: /projects/
    - text: RSS订阅
      url: /feed.xml

url: "http://www.orangeufo.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
